-- ORACLE INNER JOIN
DELETE FROM BIGTBL1;
SELECT * FROM BIGTBL1;
INSERT INTO BIGTBL1(BIGID, NUMDATA) VALUES (1, 100);
INSERT INTO BIGTBL1(BIGID, NUMDATA) VALUES (2, 200);
INSERT INTO BIGTBL1(BIGID, NUMDATA) VALUES (3, 300);

SELECT * FROM BIGTBL3;
INSERT INTO BIGTBL3(BIGID, NUMDATA) VALUES (1, 100);
INSERT INTO BIGTBL3(BIGID, NUMDATA) VALUES (2, 2000);
INSERT INTO BIGTBL3(BIGID, NUMDATA) VALUES (3, 3000);

SELECT A.BIGID, A.NUMDATA
FROM BIGTBL1 A
INNER JOIN BIGTBL3 B
ON A.BIGID = B.BIGID;

SELECT A.BIGID, A.NUMDATA
FROM BIGTBL1 A, BIGTBL3 B
WHERE A.BIGID = B.BIGID;
DROP TABLE TB_PROD;
CREATE TABLE TB_PROD(
    PROD_ID VARCHAR2(4) PRIMARY KEY,
    OWNER_ID VARCHAR2(6),
    PRICE NUMBER(30),
    CNT NUMBER(10)
);
SELECT * FROM TB_PROD;
INSERT INTO TB_PROD(PROD_ID, OWNER_ID, PRICE, CNT) VALUES ('0001', '000001', 30000, 10);
INSERT INTO TB_PROD(PROD_ID, OWNER_ID, PRICE, CNT) VALUES ('0002', '000002', 40000, 20);
INSERT INTO TB_PROD(PROD_ID, OWNER_ID, PRICE, CNT) VALUES ('0003', '000003', 50000, 30);
DROP TABLE TB_OWNER;
DELETE FROM TB_OWNER;
CREATE TABLE TB_OWNER(
    OWNER_ID VARCHAR2(6) PRIMARY KEY,
    OWNER_NO VARCHAR2(13),
    OWNER_ADDR VARCHAR2(300)
);
ALTER TABLE TB_OWNER RENAME COLUMN ONWER_ADDR TO OWNER_ADDR;
SELECT * FROM TB_OWNER;
INSERT INTO TB_OWNER(OWNER_ID, OWNER_NO, OWNER_ADDR) VALUES ('000001', '9610291111111', '마포구 상암동');
INSERT INTO TB_OWNER(OWNER_ID, OWNER_NO, OWNER_ADDR) VALUES ('000002', '9610291111112', '충남 천안시');
INSERT INTO TB_OWNER(OWNER_ID, OWNER_NO, OWNER_ADDR) VALUES ('000003', '9610291111113', '구미 옥계동');
COMMIT;

SELECT A.PROD_ID
     , A.OWNER_ID
     , A.PRICE
     , A.CNT
     , B.OWNER_ID
     , B.OWNER_NO
     , B.OWNER_ADDR
  FROM TB_PROD A 
      ,TB_OWNER B
WHERE A.OWNER_ID = B.OWNER_ID;

SELECT A.PROD_ID
     , A.OWNER_ID
     , A.PRICE
     , A.CNT
     , B.OWNER_ID
     , B.OWNER_NO
     , B.OWNER_ADDR
  FROM TB_PROD A 
  JOIN TB_OWNER B
    ON A.OWNER_ID = B.OWNER_ID
 WHERE A.PROD_ID = '0001';
 
 SELECT A.PROD_ID
     , A.OWNER_ID
     , A.PRICE
     , A.CNT
     , B.OWNER_ID
     , B.OWNER_NO
     , B.OWNER_ADDR
  FROM TB_PROD A 
  JOIN TB_OWNER B
    ON 1 = 1;

  